/**
 * Catalogue des identifiants d'action utilisés par `journaliserActionSysteme`
 * à travers tout le CMS système — sert uniquement à peupler le filtre du
 * journal d'audit (bloc 8d). Volontairement dans un fichier SANS "use server" :
 * une constante (pas une fonction) ne peut pas être exportée d'un fichier
 * "use server" (règle Next.js : uniquement des fonctions async).
 */
export const ACTIONS_AUDIT_CONNUES = [
  "restaurant.approbation",
  "restaurant.demande_correction",
  "restaurant.suspension",
  "restaurant.reactivation",
  "illustration.modification",
  "illustration.generation",
  "application.reinitialisation",
  "compte.invitation",
  "compte.revocation",
  // Écrit en base par `fn_preparer_suppression_compte` (pas par `journaliserActionSysteme`) :
  // sans cette ligne, la suppression d'un compte est journalisée mais jamais filtrable.
  "compte.suppression",
  "taxonomie.creation",
  "taxonomie.modification",
  "taxonomie.suppression",
  "contenu.page_creation",
  "contenu.page_modification",
  "contenu.page_publication",
  "contenu.page_depublication",
  "contenu.page_suppression",
  "contenu.blocs_brouillon",
  "contenu.blocs_publication",
  "contenu.blocs_restauration",
  "contenu.image_televersee",
  "contenu.banniere_creation",
  "contenu.banniere_publication",
  "contenu.banniere_depublication",
  "contenu.banniere_suppression",
  "contenu.emplacement_modification",
  "mise_en_avant.creation",
  "mise_en_avant.activation",
  "mise_en_avant.desactivation",
  "mise_en_avant.suppression",
  "coordonnees.revelation",
  "commande.support_transition",
  "systeme.attribution_role",
  "systeme.retrait_role",
  "acces.palier_attribution",
  "acces.palier_retrait",
  "parametres.modification",
  "fonctionnalite.modification",
  "design.jeton_modification",
  "design.jeton_reinitialisation",
  "design.jetons_retour_origine",
  "design.jeton_restauration",
] as const;

/** Libellés lisibles des identifiants d'action (affichés à la place du code technique ; repli : le code lui-même). */
export const LIBELLES_ACTIONS_AUDIT: Record<string, string> = {
  "restaurant.approbation": "Restaurant approuvé",
  "restaurant.demande_correction": "Correction demandée à un restaurant",
  "restaurant.suspension": "Restaurant suspendu",
  "restaurant.reactivation": "Restaurant réactivé",
  "illustration.modification": "Illustration modifiée",
  "illustration.generation": "Illustrations de démonstration générées",
  "application.reinitialisation": "Application réinitialisée",
  "compte.invitation": "Membre ajouté à une équipe",
  "compte.revocation": "Membre retiré d'une équipe",
  "compte.suppression": "Compte supprimé",
  "taxonomie.creation": "Catégorie ou quartier créé",
  "taxonomie.modification": "Catégorie ou quartier modifié",
  "taxonomie.suppression": "Catégorie ou quartier supprimé",
  "contenu.page_creation": "Page créée",
  "contenu.page_modification": "Page modifiée",
  "contenu.page_publication": "Page publiée",
  "contenu.page_depublication": "Page dépubliée",
  "contenu.page_suppression": "Page supprimée",
  "contenu.blocs_brouillon": "Brouillon d'une page à blocs enregistré",
  "contenu.blocs_publication": "Page à blocs publiée (nouvelle version)",
  "contenu.blocs_restauration": "Ancienne version remise dans le brouillon",
  "contenu.image_televersee": "Image téléversée pour une page à blocs",
  "contenu.banniere_creation": "Bannière créée",
  "contenu.banniere_publication": "Bannière publiée",
  "contenu.banniere_depublication": "Bannière dépubliée",
  "contenu.banniere_suppression": "Bannière supprimée",
  "contenu.emplacement_modification": "Texte du site modifié ou rétabli",
  "mise_en_avant.creation": "Mise en avant ajoutée",
  "mise_en_avant.activation": "Mise en avant activée",
  "mise_en_avant.desactivation": "Mise en avant désactivée",
  "mise_en_avant.suppression": "Mise en avant retirée",
  "coordonnees.revelation": "Coordonnées d'un client révélées",
  "commande.support_transition": "Statut d'une commande modifié par le support",
  "systeme.attribution_role": "Rôle système attribué",
  "systeme.retrait_role": "Rôle système retiré",
  "acces.palier_attribution": "Habilitation par palier attribuée ou remplacée",
  "acces.palier_retrait": "Habilitation par palier retirée",
  "parametres.modification": "Paramètres modifiés",
  "fonctionnalite.modification": "Fonctionnalité activée ou coupée",
  "design.jeton_modification": "Jeton de design modifié",
  "design.jeton_reinitialisation": "Jeton de design réinitialisé",
  "design.jetons_retour_origine": "Jetons de design remis à leur valeur d'origine",
  "design.jeton_restauration": "Jeton de design restauré depuis l'historique",
};

export function libelleActionAudit(action: string): string {
  return LIBELLES_ACTIONS_AUDIT[action] ?? action;
}
