/**
 * Liste fermée des motifs d'illustration (identifiants français) et leur libellé pour la console. Les dessins eux-mêmes
 * sont dans `icones.generated.ts` (Fluent Emoji Flat et Tabler Icons, licence MIT). Un test vérifie que les deux listes
 * restent identiques.
 */
export const MOTIFS: Record<string, { libelle: string; famille: "plat" | "boisson" | "dessert" | "trait" }> = {
  "riz-blanc": { libelle: "Riz blanc", famille: "plat" },
  "riz-sauce": { libelle: "Riz sauce", famille: "plat" },
  sauce: { libelle: "Marmite de sauce", famille: "plat" },
  ragout: { libelle: "Plat mijoté", famille: "plat" },
  poulet: { libelle: "Poulet", famille: "plat" },
  viande: { libelle: "Viande à l'os", famille: "plat" },
  boeuf: { libelle: "Bœuf", famille: "plat" },
  brochettes: { libelle: "Brochettes", famille: "plat" },
  poisson: { libelle: "Poisson", famille: "plat" },
  "poisson-tropical": { libelle: "Poisson braisé", famille: "plat" },
  crevette: { libelle: "Crevettes", famille: "plat" },
  crabe: { libelle: "Crabe", famille: "plat" },
  burger: { libelle: "Burger", famille: "plat" },
  frites: { libelle: "Frites", famille: "plat" },
  sandwich: { libelle: "Sandwich", famille: "plat" },
  shawarma: { libelle: "Shawarma", famille: "plat" },
  galette: { libelle: "Galette", famille: "plat" },
  pizza: { libelle: "Pizza", famille: "plat" },
  salade: { libelle: "Salade", famille: "plat" },
  oeuf: { libelle: "Œuf", famille: "plat" },
  soupe: { libelle: "Soupe", famille: "plat" },
  bol: { libelle: "Bol", famille: "plat" },
  emporter: { libelle: "À emporter", famille: "plat" },
  couvert: { libelle: "Couverts", famille: "plat" },
  "pomme-de-terre": { libelle: "Pomme de terre", famille: "plat" },
  mais: { libelle: "Maïs", famille: "plat" },
  arachide: { libelle: "Arachides", famille: "plat" },
  "patate-douce": { libelle: "Patate douce", famille: "plat" },
  banane: { libelle: "Banane plantain", famille: "plat" },
  piment: { libelle: "Piment", famille: "plat" },
  cafe: { libelle: "Café", famille: "boisson" },
  the: { libelle: "Thé", famille: "boisson" },
  "the-glace": { libelle: "Thé glacé", famille: "boisson" },
  jus: { libelle: "Jus", famille: "boisson" },
  boisson: { libelle: "Boisson", famille: "boisson" },
  cocktail: { libelle: "Cocktail", famille: "boisson" },
  croissant: { libelle: "Croissant", famille: "dessert" },
  pain: { libelle: "Pain", famille: "dessert" },
  patisserie: { libelle: "Pâtisserie", famille: "dessert" },
  tarte: { libelle: "Tarte", famille: "dessert" },
  gateau: { libelle: "Gâteau", famille: "dessert" },
  glace: { libelle: "Glace", famille: "dessert" },
  coco: { libelle: "Noix de coco", famille: "dessert" },
  mangue: { libelle: "Mangue", famille: "dessert" },
  ananas: { libelle: "Ananas", famille: "dessert" },
  "trait-grill": { libelle: "Grill (trait)", famille: "trait" },
  "trait-toque": { libelle: "Toque (trait)", famille: "trait" },
  "trait-livraison": { libelle: "Livraison (trait)", famille: "trait" },
  "trait-baguettes": { libelle: "Bol (trait)", famille: "trait" },
  "trait-pain": { libelle: "Pain (trait)", famille: "trait" },
  "trait-cafe": { libelle: "Café (trait)", famille: "trait" },
  "trait-poisson": { libelle: "Poisson (trait)", famille: "trait" },
  "trait-burger": { libelle: "Burger (trait)", famille: "trait" },
};
